# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  # config.vm.network "private_network", type: 'dhcp' #, ip: "192.168.33.10"

  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.network "forwarded_port", guest: 80, host: 8888

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false

     vb.memory = "1024"
     vb.cpus = 1
   end

   config.vm.provision "shell", privileged: true, inline: <<-SHELL
      apt-get update && apt-get -y install nginx
   SHELL
   
end
