# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", type: 'dhcp' #, ip: "192.168.33.10"

  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "2048"
     vb.cpus = 2
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
     vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
     vb.customize ["modifyvm", :id, "--vram", "128"]
     vb.customize ["modifyvm", :id, "--ioapic", "on"]
   end

   config.vm.provision "shell", privileged: true, inline: <<-SHELL
      add-apt-repository -y ppa:openjdk-r/ppa && apt-get update
   SHELL
   
   config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get -y install git wget openjdk-8-jdk nodejs
    curl -s https://install.meteor.com/ | sh
   SHELL
   
   ## !!!!!!!!! UNCOMMENT THIS STUFF TO GET UBUNTU DESKTOP FOR DEV !!!!!!!!!!!!
   # config.vm.provision "shell", privileged: false, inline: <<-SHELL
    #  mkdir -p ~/tools 
    #  sudo apt-get -y install ubuntu-desktop
    #  wget -q https://d1opms6zj7jotq.cloudfront.net/idea/ideaIU-14.1.4.tar.gz -O ~/tools/intellij.tar.gz
    #  cd ~/tools && tar -zxf intellij.tar.gz && rm intellij.tar.gz
    #  wget -q https://az764295.vo.msecnd.net/public/0.5.0/VSCode-linux-x64.zip
    #  unzip VSCode-linux-x64.zip && rm -f VSCode-linux-x64.zip
    #  wget -q http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3083_amd64.deb
    #  sudo dpkg -i sublime-text_build-3083_amd64.deb && rm -f sublime-text_build-3083_amd64.deb
   # SHELL
   
end
