letschat:
  image: sdelements/lets-chat
  links:
    - mongo
  ports:
    - 8080:8080
    - 5222:5222
  volumes:
    - /vagrant/docker-builds/lets-chat/config:/usr/src/app/config

mongo:
  image: mongo:latest